name: Deploy

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, json, mysql, pdo_mysql, gd, zip, curl

    - name: Cache Composer packages
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install

    - name: Build production assets
      run: |
        npm run core-compile
        npm run core-css-prefix
        npm run core-css-rtl
        npm run core-css-minify
        npm run admin-compile
        npm run admin-css-prefix
        npm run admin-css-rtl

    - name: Create deployment artifact
      run: |
        # Create deployment directory
        mkdir -p deploy
        
        # Copy source files
        cp -r src/* deploy/
        
        # Copy vendor directory (production dependencies only)
        cp -r vendor deploy/
        
        # Copy configuration files
        cp composer.json deploy/
        cp LICENSE deploy/
        cp COPYRIGHT.txt deploy/
        cp README.md deploy/
        
        # Remove development files
        rm -rf deploy/install
        rm -f deploy/.env.example
        
        # Create archive
        tar -czf nukeviet-${{ github.sha }}.tar.gz -C deploy .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nukeviet-build-${{ github.sha }}
        path: nukeviet-${{ github.sha }}.tar.gz
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this Release
          
          ### Features
          - See CHANGELOG.txt for detailed changes
          
          ### Installation
          1. Download the nukeviet-${{ github.sha }}.tar.gz file
          2. Extract to your web server directory
          3. Follow installation instructions in README.md
          
          ### Requirements
          - PHP 8.2+ (recommended: PHP 8.3 or 8.4)
          - MySQL 5.5+
          - Web server (Apache/Nginx)
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nukeviet-${{ github.sha }}.tar.gz
        asset_name: nukeviet-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip