name: ShareCode Module Tests

on:
  push:
    branches: [ master, dev_huy ]
    paths:
      - 'src/modules/sharecode/**'
      - 'src/admin/modules/sharecode/**'
      - 'src/themes/*/modules/sharecode/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/modules/sharecode/**'
      - 'src/admin/modules/sharecode/**'
      - 'src/themes/*/modules/sharecode/**'

jobs:
  sharecode-functionality-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nukeviet_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, json, mysql, pdo_mysql, gd, zip, curl

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup test database
      run: |
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS nukeviet_test;"
        mysql -h 127.0.0.1 -u root -proot nukeviet_test < sharecode/sharecode2\ \(1\).sql || echo "SQL file not found, skipping database setup"

    - name: Validate ShareCode Module Structure
      run: |
        echo "Checking ShareCode module structure..."
        
        # Check required files exist
        test -f "src/modules/sharecode/functions.php" || echo "Warning: ShareCode functions.php missing"
        test -f "src/modules/sharecode/admin.functions.php" || echo "Warning: ShareCode admin.functions.php missing"
        test -f "src/modules/sharecode/version.php" || echo "Warning: ShareCode version.php missing"
        test -f "src/modules/sharecode/action_mysql.php" || echo "Warning: ShareCode action_mysql.php missing"
        
        # Check admin functions
        test -d "src/admin/modules/sharecode" || echo "Warning: ShareCode admin directory missing"
        
        echo "ShareCode module structure check completed"

    - name: Test Categories Page Issues (Issue #1)
      run: |
        echo "Testing Categories page functionality..."
        
        # Check if categories admin files exist
        if [ -f "src/admin/modules/sharecode/categories.php" ]; then
          echo "✓ Categories admin file exists"
          
          # Check for static link auto-fill functionality
          if grep -q "static.*link\|alias" "src/admin/modules/sharecode/categories.php"; then
            echo "✓ Static link functionality found"
          else
            echo "❌ Static link auto-fill needs implementation"
          fi
          
          # Check for parent category handling
          if grep -q "parent\|pid" "src/admin/modules/sharecode/categories.php"; then
            echo "! Parent category functionality found - may need removal as per issue #1"
          fi
          
        else
          echo "❌ Categories admin file missing"
        fi

    - name: Test Sources Page Issues (Issue #1)  
      run: |
        echo "Testing Sources page functionality..."
        
        # Check if sources admin files exist
        if [ -f "src/admin/modules/sharecode/sources.php" ]; then
          echo "✓ Sources admin file exists"
          
          # Check for image/avatar field
          if grep -q "avatar\|image\|photo" "src/admin/modules/sharecode/sources.php"; then
            echo "✓ Image field functionality found"
          else
            echo "❌ Avatar/background image field needs implementation"
          fi
          
          # Check for select2 usage
          if grep -q "select2" "src/admin/modules/sharecode/sources.php" || grep -q "select2" "src/themes/*/modules/sharecode/admin/*.tpl" 2>/dev/null; then
            echo "✓ Select2 implementation found"
          else
            echo "❌ Select2 for keywords/tags needs implementation"
          fi
          
        else
          echo "❌ Sources admin file missing"
        fi

    - name: Test Tag Management Issues (Issue #1)
      run: |
        echo "Testing Tag management functionality..."
        
        # Check if tags admin files exist
        if [ -f "src/admin/modules/sharecode/tags.php" ]; then
          echo "✓ Tags admin file exists"
          
          # Check for CRUD operations
          if grep -q "add\|edit\|delete" "src/admin/modules/sharecode/tags.php"; then
            echo "✓ CRUD operations found in tags"
          else
            echo "❌ Tag CRUD operations need implementation"
          fi
          
        else
          echo "❌ Tags admin file missing - needs creation"
        fi

    - name: Check JavaScript and CSS Assets
      run: |
        echo "Checking ShareCode assets..."
        
        # Check for JavaScript files
        if [ -d "src/themes/admin_future/modules/sharecode" ]; then
          echo "✓ Admin theme ShareCode directory exists"
          
          if find "src/themes/admin_future/modules/sharecode" -name "*.js" | grep -q .; then
            echo "✓ JavaScript files found"
          else
            echo "! No JavaScript files found - may need for auto-fill functionality"
          fi
          
        else
          echo "❌ Admin theme ShareCode directory missing"
        fi

    - name: PHP Syntax Check for ShareCode Module
      run: |
        echo "Checking PHP syntax for ShareCode module..."
        find src/modules/sharecode/ -name "*.php" -exec php -l {} \; 2>&1 | tee sharecode_syntax.log
        
        if grep -q "Parse error\|Fatal error" sharecode_syntax.log; then
          echo "❌ PHP syntax errors found in ShareCode module"
          exit 1
        else
          echo "✓ No PHP syntax errors in ShareCode module"
        fi

    - name: Security Check for ShareCode Module
      run: |
        echo "Checking ShareCode module for security issues..."
        
        # Check for SQL injection protection
        echo "Checking for SQL injection protection..."
        if grep -r "nv_db_prepare\|quoteName\|quote" src/modules/sharecode/ --include="*.php"; then
          echo "✓ Found SQL injection protection patterns"
        else
          echo "⚠️  Warning: Limited SQL injection protection found"
        fi
        
        # Check for XSS protection
        echo "Checking for XSS protection..."
        if grep -r "htmlspecialchars\|nv_htmlspecialchars\|filter_var" src/modules/sharecode/ --include="*.php"; then
          echo "✓ Found XSS protection patterns"
        else
          echo "⚠️  Warning: Limited XSS protection found"
        fi
        
        # Check for CSRF protection
        echo "Checking for CSRF protection..."
        if grep -r "NV_CHECK_SESSION\|check_session" src/modules/sharecode/ --include="*.php"; then
          echo "✓ Found CSRF protection patterns"
        else
          echo "⚠️  Warning: Limited CSRF protection found"
        fi

    - name: Generate Test Report
      run: |
        echo "## ShareCode Module Test Report" > sharecode_test_report.md
        echo "Generated on: $(date)" >> sharecode_test_report.md
        echo "" >> sharecode_test_report.md
        echo "### Issues from GitHub #1 Status:" >> sharecode_test_report.md
        echo "- Categories Page: Static link auto-fill, parent category removal, order display" >> sharecode_test_report.md
        echo "- Sources Page: Avatar field, auto-fill, keywords field, description improvements" >> sharecode_test_report.md  
        echo "- Tag Management: Add/edit/delete functionality" >> sharecode_test_report.md
        echo "- Logs Deletion: Activity display issues" >> sharecode_test_report.md
        echo "" >> sharecode_test_report.md
        echo "### Test Results:" >> sharecode_test_report.md
        echo "See workflow logs for detailed results" >> sharecode_test_report.md

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: sharecode-test-report
        path: sharecode_test_report.md